project_id = "tpsseyzezbmfxydeaibr"

[functions.chat]
verify_jwt = true

[functions.generate-longcat]
verify_jwt = true

[functions.generate-emu]
verify_jwt = true

[functions.export-social]
verify_jwt = true

[functions.generate-vertex-ai]
verify_jwt = true

[functions.adgen-orchestrator]
verify_jwt = true