apiVersion: v1
kind: Service
metadata:
  name: colony-api
  namespace: colonyos
spec:
  selector:
    app: colony-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: grpc
      port: 50051
      targetPort: 50051
  type: LoadBalancer
